name: deploy work 2
on: 
  push:
    branches: [main,master]
permissions:
  pages: write
  id-token: write
jobs:
  deploy-and-build:
    runs-on: ubuntu-latest
    steps:
    -  name: checkout 
       uses: actions/checkout@v4
    -  name: configure pages
       uses: actions/configure-pages@v4
    -  name: upload artifacts
       uses: actions/upload-pages-artifact@v3
       with:
         path: "."
    -  name: deploy pages
       uses: actions/deploy-pages@v4
    
       
